/**
 * Type shim for the virtual RSC entry module generated by vinext at build time.
 *
 * The default export is the request handler. Named exports `__assetPrefix`
 * and `__basePath` are inlined string literals from next.config, while
 * `__hasPagesDir` exposes whether the build includes a Pages Router surface.
 * See `entries/app-rsc-entry.ts` for the generator that emits these.
 */
declare module "virtual:vinext-rsc-entry" {
  const rscHandler: (
    request: Request,
    ctx?: unknown,
  ) => Promise<Response | null | undefined | string>;
  export default rscHandler;
  export const __assetPrefix: string;
  export const __basePath: string;
  export const __hasPagesDir: boolean;
}
